version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7

    steps:
      - checkout
      - run:
          name: Install python desps in venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install "django<1.12" "selenium<4"
    
      - run:
          name: "run tests"
          command: |
            python manage.py test

          
