version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7

    steps:
      - checkout
      - run:
        python3 -m venv venv
        . venv/bin/activate
        run: pip install "django<1.12" "selenium<4"
    
      - run:
          name: "run tests"
          command: |
            python manage.py test

          
